# Generated by Django 5.1.2 on 2024-11-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_alter_video_num_likes_alter_video_num_views_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Publicado em'),
        ),
    ]
